import PublicPortalHeader from "@/components/PublicPortalHeader";
import { Bell, Loader2 } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

export default function Notifications() {
  const [email, setEmail] = useState(() => sessionStorage.getItem("samadhan-citizen-email") ?? ""); const query = trpc.workflow.notifications.useQuery({ recipientEmail: email || "placeholder@example.invalid" }, { enabled: Boolean(email) });
  return <main className="min-h-screen bg-[#f1eadc] text-[#0c3023]" style={{ backgroundImage: "url('/manus-storage/samadhan-paper-grain_46302c3f.jpg')", backgroundSize: "cover" }}><PublicPortalHeader /><section className="px-6 py-10 sm:px-10 lg:px-[5rem]"><div className="mx-auto max-w-[64rem]"><p className="font-mono-ui text-[0.62rem] font-semibold uppercase tracking-[0.13em] text-[#c64b22]">Workflow notification center</p><h1 className="mt-4 font-display text-[4.2rem] leading-[0.86] tracking-[-0.04em]">Status handoffs.</h1><p className="mt-5 font-body text-[0.88rem] text-[#53675d]">Enter the email used in the demo workflow to review assignment, delivery, closeout, and confirmation notifications.</p><label className="mt-8 block max-w-md"><span className="font-mono-ui text-[0.57rem] font-semibold uppercase tracking-[0.1em]">Recipient email</span><input type="email" value={email} onChange={event => { setEmail(event.target.value); sessionStorage.setItem("samadhan-citizen-email", event.target.value); }} className="citizen-input mt-2" placeholder="you@example.com" /></label>{!email ? <Empty label="Enter an email to view workflow notices." /> : query.isLoading ? <Loading /> : query.isError ? <Failure message={query.error.message} retry={() => void query.refetch()} /> : (query.data ?? []).length === 0 ? <Empty label="No workflow notifications are recorded for this email." /> : <div className="mt-8 space-y-3">{query.data?.map(item => <a key={item.id} href={item.href || "#top"} className="block border border-[#a58c6d]/55 bg-[#f8f2e8]/25 p-5 hover:bg-[#e9dfcd]/50"><div className="flex items-start gap-4"><Bell className="mt-1 text-[#c94a20]" size={19} /><div><h2 className="font-display text-[1.5rem] leading-none">{item.title}</h2><p className="mt-3 font-body text-[0.8rem] leading-relaxed text-[#52675d]">{item.body}</p><p className="mt-3 font-mono-ui text-[0.52rem] uppercase tracking-[0.08em] text-[#64776d]">{item.createdAt ? new Date(item.createdAt).toLocaleString() : ""}</p></div></div></a>)}</div>}</div></section></main>;
}
function Loading() { return <div className="mt-8 flex items-center gap-3 font-body text-[#52675d]"><Loader2 className="animate-spin" size={18} />Loading notifications…</div>; }
function Empty({ label }: { label: string }) { return <div className="mt-8 border border-dashed border-[#a58c6d]/55 p-8 text-center font-body text-[0.8rem] text-[#586d63]">{label}</div>; }
function Failure({ message, retry }: { message: string; retry: () => void }) { return <div role="alert" className="mt-8 border border-[#bd5a38]/60 bg-[#f7e2d6]/35 p-6"><p className="font-body text-[0.76rem] text-[#934325]">{message}</p><button type="button" onClick={retry} className="mt-3 border border-[#bd5a38]/60 px-3 py-2 font-mono-ui text-[0.54rem] uppercase tracking-[0.08em] text-[#a54426]">Retry</button></div>; }
